services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql

volumes:
  postgresdata:
