services:
  appserver:
    container_name: server
    hostname: localhost
    image: saralalerner/basic-spring:1001
    ports:
      - "8080:8080"
  postgres:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    volumes:
      - postgresdata18:/var/lib/postgresql
    privileged: true
volumes:
  postgresdata18:
